### ISSUE TITLE
PUT method describe 200 response, but in reality it returns 204

### ISSUE THREAD

**Issue by pmoleri** [IgniteUI/NorthwindAPI#6]
Swagger:
![image](https://user-images.githubusercontent.com/12942794/213266856-f1f66df7-f79b-4a61-902c-d884fcfabf18.png)

Actual response:
204 with empty response body

**Comment by Svetloslav15** [comment]
@pmoleri It will return 204 when the id is invalid because it cannot find such item and it returns Ok(null).
