### ISSUE TITLE
Update/PUT endpoints return Ok(null) instead of NotFound() when the model.id value doesn't match an existint entry 

### ISSUE THREAD

**Issue by gmartinezig** [IgniteUI/NorthwindAPI#8]
![image](https://user-images.githubusercontent.com/12627640/220192233-4a6e3ef7-b27f-46ee-ab07-a0412aa87093.png)

**Comment by pmoleri** [comment]
Sample API from Microsoft docs:
https://learn.microsoft.com/en-us/aspnet/core/tutorials/min-web-api?view=aspnetcore-7.0&tabs=visual-studio#add-the-api-code

This is "Minimial API" instead of "Controller", but the point is just to check the response values for GET, PUT, DELETE
